2023-05-28 17:02:58,080:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-05-28 17:02:58,084:INFO:discord.client: logging in using static token
2023-05-28 17:02:59,021:INFO:discord.gateway: Shard ID None has sent the IDENTIFY payload.
2023-05-28 17:02:59,303:INFO:discord.gateway: Shard ID None has connected to Gateway: ["gateway-prd-us-east1-b-3nx9",{"micros":178028,"calls":["id_created",{"micros":1859,"calls":[]},"session_lookup_time",{"micros":3597,"calls":[]},"session_lookup_finished",{"micros":17,"calls":[]},"discord-sessions-prd-2-52",{"micros":171643,"calls":["start_session",{"micros":149472,"calls":["discord-api-56b8b9bbd9-tf7sj",{"micros":142456,"calls":["get_user",{"micros":36505},"get_guilds",{"micros":31047},"send_scheduled_deletion_message",{"micros":10},"guild_join_requests",{"micros":2},"authorized_ip_coro",{"micros":14}]}]},"starting_guild_connect",{"micros":173,"calls":[]},"presence_started",{"micros":250,"calls":[]},"guilds_started",{"micros":81,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":21633,"calls":[]},"connect_finished",{"micros":21639,"calls":[]},"build_ready",{"micros":24,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":1,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}] (Session ID: af8a21c828cbce1c62de880c39806142).
2023-05-28 18:08:40,095:INFO:discord.gateway: Websocket closed with 1006, attempting a reconnect.
2023-05-28 18:08:40,095:INFO:discord.client: Got a request to RESUME the websocket.
2023-05-28 18:08:40,097:ERROR:discord.client: Attempting a reconnect in 1.45s
Traceback (most recent call last):
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-28 18:08:45,527:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
2023-05-28 18:08:45,671:INFO:discord.gateway: Shard ID None has successfully RESUMED session af8a21c828cbce1c62de880c39806142 under trace ["gateway-prd-us-east1-c-fps5",{"micros":871,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":472,"calls":[]},"session_lookup_finished",{"micros":18,"calls":[]},"discord-sessions-prd-2-52",{"micros":28}]}].
2023-05-28 19:24:55,994:INFO:discord.client: Got a request to RESUME the websocket.
2023-05-28 19:24:56,385:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
2023-05-28 19:24:56,444:INFO:discord.gateway: Shard ID None has successfully RESUMED session af8a21c828cbce1c62de880c39806142 under trace ["gateway-prd-us-east1-b-w0dl",{"micros":542,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":268,"calls":[]},"session_lookup_finished",{"micros":16,"calls":[]},"discord-sessions-prd-2-52",{"micros":23}]}].
2023-05-28 22:00:54,722:INFO:discord.client: Got a request to RESUME the websocket.
2023-05-28 22:00:55,115:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
2023-05-28 22:00:55,190:INFO:discord.gateway: Shard ID None has successfully RESUMED session af8a21c828cbce1c62de880c39806142 under trace ["gateway-prd-us-east1-b-w0dl",{"micros":4363,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":4129,"calls":[]},"session_lookup_finished",{"micros":18,"calls":[]},"discord-sessions-prd-2-52",{"micros":20}]}].
2023-05-29 00:11:07,278:INFO:discord.client: Got a request to RESUME the websocket.
2023-05-29 00:11:07,607:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
2023-05-29 00:11:07,673:INFO:discord.gateway: Shard ID None has successfully RESUMED session af8a21c828cbce1c62de880c39806142 under trace ["gateway-prd-us-east1-d-1fv6",{"micros":708,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":374,"calls":[]},"session_lookup_finished",{"micros":13,"calls":[]},"discord-sessions-prd-2-52",{"micros":25}]}].
2023-05-29 00:59:19,235:INFO:discord.client: Got a request to RESUME the websocket.
2023-05-29 00:59:21,527:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
2023-05-29 00:59:21,626:INFO:discord.gateway: Shard ID None has successfully RESUMED session af8a21c828cbce1c62de880c39806142 under trace ["gateway-prd-us-east1-d-hskx",{"micros":591,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":293,"calls":[]},"session_lookup_finished",{"micros":15,"calls":[]},"discord-sessions-prd-2-52",{"micros":26}]}].
2023-05-29 04:38:36,782:INFO:discord.client: Got a request to RESUME the websocket.
2023-05-29 04:38:37,167:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
2023-05-29 04:38:37,230:INFO:discord.gateway: Shard ID None has successfully RESUMED session af8a21c828cbce1c62de880c39806142 under trace ["gateway-prd-us-east1-d-mdh8",{"micros":652,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":351,"calls":[]},"session_lookup_finished",{"micros":15,"calls":[]},"discord-sessions-prd-2-52",{"micros":21}]}].
2023-05-29 05:21:09,060:INFO:discord.gateway: Websocket closed with 1006, attempting a reconnect.
2023-05-29 05:21:09,061:INFO:discord.client: Got a request to RESUME the websocket.
2023-05-29 05:21:09,439:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
2023-05-29 05:21:09,540:INFO:discord.gateway: Shard ID None has successfully RESUMED session af8a21c828cbce1c62de880c39806142 under trace ["gateway-prd-us-east1-b-hs9h",{"micros":7804,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":7535,"calls":[]},"session_lookup_finished",{"micros":13,"calls":[]},"discord-sessions-prd-2-52",{"micros":23}]}].
2023-05-29 07:09:49,834:INFO:discord.client: Got a request to RESUME the websocket.
2023-05-29 07:09:50,236:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
2023-05-29 07:09:50,303:INFO:discord.gateway: Shard ID None has successfully RESUMED session af8a21c828cbce1c62de880c39806142 under trace ["gateway-prd-us-east1-b-ztkx",{"micros":4905,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":4631,"calls":[]},"session_lookup_finished",{"micros":16,"calls":[]},"discord-sessions-prd-2-52",{"micros":19}]}].
2023-05-29 08:59:15,350:INFO:discord.client: Got a request to RESUME the websocket.
2023-05-29 08:59:15,714:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
2023-05-29 08:59:15,774:INFO:discord.gateway: Shard ID None has successfully RESUMED session af8a21c828cbce1c62de880c39806142 under trace ["gateway-prd-us-east1-d-v0mh",{"micros":686,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":333,"calls":[]},"session_lookup_finished",{"micros":14,"calls":[]},"discord-sessions-prd-2-52",{"micros":24}]}].
2023-05-29 12:00:44,037:INFO:discord.client: Got a request to RESUME the websocket.
2023-05-29 12:00:44,381:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
2023-05-29 12:00:44,444:INFO:discord.gateway: Shard ID None has successfully RESUMED session af8a21c828cbce1c62de880c39806142 under trace ["gateway-prd-us-east1-c-2b23",{"micros":764,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":387,"calls":[]},"session_lookup_finished",{"micros":16,"calls":[]},"discord-sessions-prd-2-52",{"micros":25}]}].
2023-05-29 12:55:32,947:INFO:discord.client: Got a request to RESUME the websocket.
2023-05-29 12:55:44,024:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
2023-05-29 12:55:44,099:INFO:discord.gateway: Shard ID None has successfully RESUMED session af8a21c828cbce1c62de880c39806142 under trace ["gateway-prd-us-east1-b-h0c0",{"micros":681,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":195,"calls":[]},"session_lookup_finished",{"micros":28,"calls":[]},"discord-sessions-prd-2-52",{"micros":42}]}].
2023-05-29 14:26:14,928:INFO:discord.client: Got a request to RESUME the websocket.
2023-05-29 14:26:15,445:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
2023-05-29 14:26:15,509:INFO:discord.gateway: Shard ID None has successfully RESUMED session af8a21c828cbce1c62de880c39806142 under trace ["gateway-prd-us-east1-d-6gbq",{"micros":790,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":419,"calls":[]},"session_lookup_finished",{"micros":14,"calls":[]},"discord-sessions-prd-2-52",{"micros":27}]}].
2023-05-29 15:06:44,240:INFO:discord.client: Received signal to terminate bot and event loop.
2023-05-29 15:06:44,240:INFO:discord.client: Cleaning up tasks.
2023-05-29 15:06:44,240:INFO:discord.client: Cleaning up after 1 tasks.
2023-05-29 15:06:44,299:INFO:discord.client: All tasks finished cancelling.
2023-05-29 15:06:44,299:INFO:discord.client: Closing the event loop.
